version: '2'

services:
  axonserver:
    image: axoniq/axonserver
    ports:
    - 8124:8124
    - 8024:8024
    networks:
    - swa
    logging:
      driver: none
  rabbitmq:
    build: docker/rabbitmq
    volumes:
      - ./docker/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro
      - ./docker/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
    logging:
      driver: none
    ports:
    - 4369:4369
    - 5671:5671
    - 5672:5672
    - 15671:15671
    - 15672:15672
    - 25672:25672
    networks:
    - swa
  python-service:
    build: python-service
    networks:
    - swa
networks:
  swa:
    external:
      name: swa
